version: '3.4'

services:
  ti_boot:
    image: ${DOCKER_REGISTRY-}tiboot
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
    depends_on:
      - db
    networks:
      - default
  
  db:
    image: mysql
    ports: 
      - 3307:3306
    environment:
      MYSQL_DATABASE: ChatBoot
      MYSQL_USER: root
      MYSQL_PASSWORD: Schulze.10
      MYSQL_ROOT_PASSWORD: Schulze.10
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default

  adminer:
    image: adminer
    ports:
       - 8080:8080
    networks:
    - default