version: '3.4'

services:
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ChatBoot
            MYSQL_USER: root
            MYSQL_PASSWORD: Schulze.10
            MYSQL_ROOT_PASSWORD: Schulze.10
        volumes:
        #Note that this is for Windows.
            - //C/Work/Dockershared/mysql:/var/lib/mysql   
        networks:
            - default
   
    tiboot:
        image: ${DOCKER_REGISTRY}tiboot
        build:
          context: .
          dockerfile: TI_BOOT/Dockerfile
        links:
          - db:db
        ports:
          - 8001:80
        restart: always

    phpmyadmin:
          image: phpmyadmin/phpmyadmin
          links: 
              - db:db
          ports:
              - 8000:80
          environment:
            MYSQL_DATABASE: ChatBoot
            MYSQL_USER: root
            MYSQL_PASSWORD: Schulze.10
            MYSQL_ROOT_PASSWORD: Schulze.10
      
